### ISSUE TITLE
Separated view doesn't show floating-point numbers

### ISSUE THREAD

**Issue by NewbieProger** [holomekc/wiremock#23]
Hello,

Today we noticed such a thing that the 'Separated' mode does not display floating-point numbers in the body of the outgoing request, when the display through 'RAW' this shows that it is very misleading. 

In addition, in wiremock logs (via docker), the display of 'Request does not match' does not show why it couldn't find the stub for this request

![image (3)](https://user-images.githubusercontent.com/34659664/156644173-9ae64e05-4aa0-4cb1-9f28-3097c2d2c995.png)
![image (4)](https://user-images.githubusercontent.com/34659664/156644184-c75302b3-7ef0-43a9-ae45-d2924b73938f.png)
![image (5)](https://user-images.githubusercontent.com/34659664/156644197-e3fb690d-1e7a-48c5-bd4c-6e6fad6b820e.png)

**Comment by holomekc** [comment]
I will take a look after easter vacation. Sorry for the extreme late response.

**Comment by holomekc** [comment]
Hi ok let us start with the decimal precision topic:
I am not sure if I can do much about that. The reason why the .0 is removed is due to pretty printing the json. I am currently using vkbeautify (because it also supports xml) which uses JSON.parse and JSON.stringify to pretty print. So the string is first parsed into an object and then pretty printed to a string again. The precision is getting lost when parsed due to javascript and IEEE 754, which does not have a representation for .0 or .000.... I would be forced to create a custom parser which resolves .0 to a string with quotes to keep precision and then convert it back removing quotes. 

Regarding logging not matched requests. I am not 100% sure which logs are missing:
![image](https://user-images.githubusercontent.com/30546982/164189487-3b3882d5-224f-44b6-a14f-559c7ac21743.png)
I guess this is more a general wiremock topic. I did not really change the logging. You can also try verbose option if you want to  see more details.
