### ISSUE TITLE
Permitted system keys

### ISSUE THREAD

**Issue by NewbieProger** [holomekc/wiremock#36]
![image](https://user-images.githubusercontent.com/34659664/230592808-b962deb6-ee00-4e38-b398-fe526d48ffca.png)

How to pass my custom variable like: `WIREMOCK_MY_VAR` accroding on new format of envs https://wiremock.org/docs/running-standalone/

When i try set  `WIREMOCK_MY_VAR` i got exception 'is not defined'

**Comment by holomekc** [comment]
Hi,

sorry for the late answer. At the moment you can workaround it by defining the following environment variables:

```
WIREMOCK_PERMITTED_SYSTEM_KEYS: w.*
W_MY_VAR: test
```

I need to check if I need to change my environment variable adjustements or if I can work around it so that it does not matter. At the moment it creates a clash between the command line options extracted from environment variables and environment variables for the systemValue feature.

I will take a look.

Br,
Chris

**Comment by holomekc** [comment]
Check readme for information regarding configuration. Sorry for the very late response

**Comment by NewbieProger** [comment]
Thanks!
