### ISSUE TITLE
[Feature Requirement]A folder or tree view for classifying the mappings from UI

### ISSUE THREAD

**Issue by cookie220** [holomekc/wiremock#4]
## Feature requests

I want to classify the mappings into different catalogs.
eg:

UserMappings
     -  mapping1
     - mapping2
ProductMappings
    - mapping3
    - mapping4

or folders to store the mappings

**Comment by holomekc** [comment]
Hi. Sorry for my very late response. This would require to extend the data model. I can take a look if wiremock is tolerant enough to let me do such things. Due to work I am quite bussy and to be honest I do not want to sit the whole day infront of my pc. But I will take a look. I cannot tell you how much time I need.

**Comment by cookie220** [comment]
Hi @holomekc Thanks for your reply, you can take time to try it when you are free.

**Comment by holomekc** [comment]
Hi. I know this is very very late. but I added a "test" mapping feature and thought maybe I can think about your feature request.

But I have a hard time figure out how this could work properly. The combination of tree view and pagination seems like a bad idea. I found something like this:
https://ej2.syncfusion.com/demos/#/material/tree-grid/default-paging.html

But I do not like it that much. When you select show 5 at the bottom and then expand the second entry, and then go to the next side you do not know anymore to which group the items contain.

Other option would be to remove pagination. But this is not that great for rendering. Also it should not be necessary to group mappings. Postman uses tree view without pagination.

I also thought about having a dropdown for a group and then show pagination of all items in this group. But not sure if I like that. This is actually the easiest solution because I do not need to change much. Just need to filter the mappings properly. Also an all option would be an idea as well, this would work better with the search. But I am not sure if this is what you expect ;)

Any further ideas?

**Comment by cookie220** [comment]
@holomekc Hope you are well! Thanks for your reply. I also looking for some UI of tree view.
I think the most suitable for the project should be[ this link](https://dribbble.com/shots/7797656-Tree-View) from my findings. The style is quite similar to wiremock's ui. We can change the background color to the yelllow & blue that is the same to wiremock ui. And it seems we also can drag and move the items.
But the simplest way is to build a basic tree view like [this link](https://www.telerik.com/kendo-vue-ui/components/treeview-wrapper/) and [this one](https://demos.shieldui.com/web/treeview/basic-usage) as you said.
This is based on your time, if you decide to develop one of them, please let me know. I can help to test any beta version of the build. Keep in touch. Thanks.

**Comment by holomekc** [comment]
Ok. I will check that. Regarding data model, I think I will use the metadata object:

http://wiremock.org/docs/stub-metadata/

```json
{
  "metadata": {
    "gui": {
      "group": "UserMappings"
    }
  }
}
```

Multiple levels?

```json
{
  "metadata": {
    "gui": {
      "group": "UserMappings.2ndLevel"
    }
  }
}
```

I first thought to create dependencies in the mapping like defining the parent. But this makes no sense. The tree is more like folders and the leaves are the mappings. So I am trying to prevent to store information outside the actual mappings. Otherwise you cannot create that structure when writing mappings via json.

This also allows to keep some code I already have. E.g. The search can work the same. Just filtering the mappings and ui checks for group and creates the tree structure. I guess.

If i try to add drag-and-drop maybe I can also add something like order of mappings. But this would again be just a visual thing.

Regarding pagination. I guess I can only do that for top level.

**Comment by cookie220** [comment]
Thanks, I think the most common using should be:

option 1:

**Function A:**

>    mapping A
>    mapping B

**Function B**

>    mapping C
>    mapping D

option 2:

**Funciton A**
      **Get**:

>       mapping A - get
>       mapping B - get
**Post**:

>      mapping A - post
>      mapping B - post

**Funciton B**
      **Get**:

>       mapping C - get
>       mapping D - get

      **Post**:

>      mapping C - post
>      mapping D - post


of course, the option 2 has 3 levels. Function -> Action(GET/POST)->mapping.  It may be more difficult.

**Comment by holomekc** [comment]
Ok so far so good:
![image](https://user-images.githubusercontent.com/30546982/151453132-31e213b3-f4b1-4d5f-a5af-433187865d12.png)

Search is also working without any changes, which makes me happy :).

Still not sure what I do with the selection when something is collapsed. I think when you search or navigate via link to a mapping the expectation is that this mapping is actually also visible in the tree view. Otherwise it is kind of annoying to search for it. 

Also need to check that the tree is extended properly. Currently it is recreated all the time which is slower and results in everything collapsing 

Also not sure regaring colors and lines. The second darker blue color is shown when hovering over a folder. Feedback would be awesome. 

I also made the padding around the elements smaller. Otherwise too much space got lost. It is not much but due to tree structure I think this makes more sense:
![image](https://user-images.githubusercontent.com/30546982/151453470-c9c7bd58-2898-472c-bb25-d34ce6d35b03.png)
![image](https://user-images.githubusercontent.com/30546982/151453507-a363758c-511c-4ec8-98bb-038df3cf9738.png)

**Comment by holomekc** [comment]
Folder view is part of 2.32.0.2

- When loading files from disk the directory structure should be applied automatically. 
- When creating new mappings via ui and setting up metadata it should also store the file at this location.
- Files which are stored already are not changed. This would require that I move files around. I am not yet sure if this is a good idea. 

No drag-and-drop yet. I have a branch were I tested it. It is somehow working but due to the current situation that mappings are not sorted this looks very strange, because mappings might jump after releasing depending on order afterwards. To achieve that I would need a proper sorting strategy also in wiremock.
