### ISSUE TITLE
Enhancement - Option to use stub name instead of urlPath of the stub

### ISSUE THREAD

**Issue by Crunsky** [holomekc/wiremock#49]
Hi !

Thank you for your work !

I was wondering if you could possibly add an option (like a toggle button or anything else) in the tree-view to display stubs using their name instead of the urlPath that is defined for the stub ?

In my case, I have multiple stubs using the same urlPath used for various use cases and I think that it could be useful to identify them using their name.

What do you think about this suggestion ?

**Comment by holomekc** [comment]
Hi @Crunsky,

I think this is a great idea. I can show the name if it is set and if it is not set the url is shown:
name > url > urlPattern > urlPath > urlPathPattern

I think this should be the default and maybe as you said a config option. Not sure if this is really necessary, because I think if somebody already makes the effort to define a name for a mapping, then this should be shown.

Br,
Chris

**Comment by holomekc** [comment]
E.g:
<img width="1020" alt="image" src="https://github.com/holomekc/wiremock/assets/30546982/a6762866-9475-43ec-b6bc-b6305071294f">
and
<img width="1017" alt="image" src="https://github.com/holomekc/wiremock/assets/30546982/95174077-ad78-4ee6-94c8-601f55fcf521">

**Comment by holomekc** [comment]
I moved the url to the subtitle section when the name is set. Not yet sure if this is good, but I think I like this.

<img width="1023" alt="image" src="https://github.com/holomekc/wiremock/assets/30546982/c9cfdfc4-b9b7-4b41-98bb-3e5a26c951c7">

**Comment by holomekc** [comment]
Hi @Crunsky ,

you can check 3.3.1.4 and if this matches your expectation.

**Comment by Crunsky** [comment]
Hi @holomekc 
Thanks for this new feature 👍 

It is perfect for me 🤩 🙏
